import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Tapistrii",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body 
        className={inter.className + 'min-h-[100vh] bg-black text-white'} 
      >
        <main className='pb-[70px]'>
          { children }
        </main>
      </body>
    </html>
  );
}
